sudo: false
language: node_js
node_js:
- 8
- 10
- 12
branches:
  only:
  - master
cache:
  yarn: true
  npm: true
install:
- npm install
script:
- npm run tslint
- npm run build
- npm run test-with-coveralls
jobs:
  include:
  - stage: documentation
    node_js: 12
    script:
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
    - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
  - stage: npm release
    node_js: 12
    script: skip
    deploy:
      provider: npm
      email: mail@betula.co
      api_key: "$NPM_TOKEN"
      on:
        branch: master
      skip_cleanup: true
notifications:
  email:
    recipients:
    - mail@betula.co
    on_failure: always
